
server.port = 8888
logging.config = classpath:log4j2-spring.xml

dubbo.consumer.timeout=60000
dubbo.config.multiple=true
dubbo.reference.check=false
dubbo.registries.corgi.id=registry1
dubbo.registries.corgi.protocol=zookeeper
dubbo.registries.corgi.address =localhost:2181
provider.version=1.0.0
#spring.redis.host=localhost
#spring.redis.port=6379

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=test
#spring.rabbitmq.password=test
# 开启ACK
#spring.rabbitmq.listener.direct.acknowledge-mode=manual
#spring.rabbitmq.listener.simple.acknowledge-mode=manual

